ADNUG.Lightning.Web/Models/DataTransferObjects/DriveFolderDto.cs
using Microsoft.AspNetCore.Html;

namespace ADNUG.Lightning.Web.Models.DataTransferObjects
{
    public class DriveFolderDto
    {
        public IHtmlContent Name { get; set; }
        public string FullPath { get; set; }
        public string Icon { get; set; }
        public bool Empty { get; set; }
    }
}

ADNUG.Lightning.Web/Models/DataTransferObjects/DriveInfoDto.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Html;

namespace ADNUG.Lightning.Web.Models.DataTransferObjects
{
	public class DriveInfoDto
    {
        public IHtmlContent BreadCrumbTrail { get; set; }
        public IEnumerable<IEnumerable<DriveFolderDto>> FolderGrid { get; set; }
    }
}

ADNUG.Lightning.Web/Models/HardDriveViewModel.cs
using System.Collections.Generic;
using ADNUG.Lightning.Web.Models.DataTransferObjects;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ADNUG.Lightning.Web.Models
{
	public class HardDriveViewModel
    {
        public IList<List<DriveFolderDto>> DriveFolders { get; set; }
        public IEnumerable<SelectListItem> DriveLetters { get; set; }

        public string SelectedDriveId { get; set; }
    }
}

ADNUG.Lightning.Web/Models/PersonEditModel.cs
using System.ComponentModel;

namespace ADNUG.Lightning.Web.Models
{
    public class PersonEditModel
    {
		[DisplayName("First Name")]
	    public string FirstName { get; set; }
	    [DisplayName("Last Name")]
		public string LastName { get; set; }
	    public int Age { get; set; }
    }
}

ADNUG.Lightning.Web/Controllers/FolderBrowserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADNUG.Lightning.Hardware.Services;
using ADNUG.Lightning.Web.Infrastructure.Extensions;
using ADNUG.Lightning.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ADNUG.Lightning.Web.Controllers
{
	public class FolderBrowserController : Controller
    {
	    private readonly IHardDriveInfoService _hardDriveInfoService;

	    public FolderBrowserController(IHardDriveInfoService hardDriveInfoService)
	    {
		    _hardDriveInfoService = hardDriveInfoService;
	    }


		public async Task<IActionResult> Index()
        {
	        var hardDrives = await _hardDriveInfoService.GetHardDrivesAsync();

	        var hardDriveViewModel = new HardDriveViewModel
	        {
		        DriveLetters = hardDrives
			        .Select((d, i) =>
			        {
				        var driveLetter = d.Name.Substring(0, 1);
				        return new KeyValuePair<string, string>(driveLetter, driveLetter);
			        })
			        .ToSelectList(),
		        SelectedDriveId = @"C:\"
	        };

	        return View(hardDriveViewModel);
		}


	    [HttpGet]
	    public async Task<IActionResult> IndexWithId(string selectedDriveId)
	    {
		    var hardDrives = await _hardDriveInfoService.GetHardDrivesAsync();

		    var hardDriveViewModel = new HardDriveViewModel
		    {
			    DriveLetters = hardDrives
				    .Select((d, i) =>
				    {
					    var driveLetter = d.Name.Substring(0, 1);
					    return new KeyValuePair<string, string>(driveLetter, driveLetter);
				    })
				    .ToSelectList(),
			    SelectedDriveId = selectedDriveId + @":\"
		    };

		    return View("Index", hardDriveViewModel);
	    }

	}
}

ADNUG.Lightning.Web/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADNUG.Lightning.Hardware.Services;
using ADNUG.Lightning.Web.Infrastructure.Extensions;
using ADNUG.Lightning.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ADNUG.Lightning.Web.Controllers
{
	public class HomeController : Controller
    {
	    private readonly IHardDriveInfoService _hardDriveInfoService;

	    public HomeController(IHardDriveInfoService hardDriveInfoService)
	    {
		    _hardDriveInfoService = hardDriveInfoService;
	    }


		public IActionResult Index()
        {
            return View();
        }


	    [HttpGet]
	    public async Task<IActionResult> IndexWithId(string selectedDriveId)
	    {
		    var hardDrives = await _hardDriveInfoService.GetHardDrivesAsync();

		    var hardDriveViewModel = new HardDriveViewModel
		    {
			    DriveLetters = hardDrives
				    .Select((d, i) =>
				    {
					    var driveLetter = d.Name.Substring(0, 1);
					    return new KeyValuePair<string, string>(driveLetter, driveLetter);
				    })
				    .ToSelectList(),
			    SelectedDriveId = selectedDriveId + @":\"
		    };

		    return View("Index", hardDriveViewModel);
	    }

	}
}

ADNUG.Lightning.Web/Controllers/PersonController.cs
using ADNUG.Lightning.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace ADNUG.Lightning.Web.Controllers
{
    public class PersonController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
	        var person = new PersonEditModel
	        {
		        Age = 54,
		        FirstName = "Dutch",
		        LastName = "Dixon",
	        };

            return View(person);
        }

	    public IActionResult BuiltInTagHelpers()
	    {
		    var person = new PersonEditModel
		    {
			    Age = 54,
			    FirstName = "Dutch",
			    LastName = "Dixon",
		    };

		    return View(person);
	    }
	}
}

ADNUG.Lightning.Web/Controllers/api/HardDriveController.cs
using System.Threading.Tasks;
using ADNUG.Lightning.Hardware.Model;
using ADNUG.Lightning.Hardware.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ADNUG.Lightning.Web.Controllers.api
{
    [Route("api/[controller]")]
    public class HardDriveController : Controller
    {
        private readonly IHardDriveInfoService _hardDriveInfoService;

        public HardDriveController(IHardDriveInfoService hardDriveInfoService, ILoggerFactory loggerFactory)
        {
            _hardDriveInfoService = hardDriveInfoService;
        }

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            return Ok(await _hardDriveInfoService.GetDirectoryContentsAsync(@"D:\"));
        }


	    [HttpPost]
	    [Route("[action]")]
	    public IActionResult GetContents([FromBody] DriveFolder model)
	    {
		    return ViewComponent("DirectoryGrid", new {fullPath = model.FullPath});
	    }
    }
}

ADNUG.Lightning.Web/Views/FolderBrowser/Index.cshtml
@using ADNUG.Lightning.Web.Models
@model ADNUG.Lightning.Web.Models.HardDriveViewModel

<div class="row">

    <div class="col-xs-offset-3 col-xs-6">
        <form asp-controller="FolderBrowser" asp-action="IndexWithId" asp-antiforgery="false" method="get" class="form">

            <div class="form-group">
                <label asp-for="SelectedDriveId">Select a drive and Click the Submit Drive button</label>
                <select asp-for="SelectedDriveId" asp-items="Model.DriveLetters" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit Drive" class="btn btn-default" />
            </div>
        </form>
    </div>

    <div id="dirList" class="col-xs-offset-3 col-xs-6">
        @await Component.InvokeAsync("DirectoryGrid", new { fullPath = @Model.SelectedDriveId })
    </div>

</div>

ADNUG.Lightning.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    
    <input type="text" 
           name="EmailAddress" 
           ad-form-input 
           ad-label-text="Email Address" 
           ad-name-id="exampleInputEmail1" />
    
</div>

ADNUG.Lightning.Web/Views/Person/BuiltInTagHelpers.cshtml
@using ADNUG.Lightning.Web.Models
@model ADNUG.Lightning.Web.Models.PersonEditModel

@{
    ViewBag.Title = "Built In Tag Helpers Example";
    Layout = "_Layout";
}

<h2>Built In Tag Helpers Example</h2>

<form asp-controller="Person" asp-action="BuiltInTagHelpers" method="post" asp-antiforgery="true">

    <div>
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" type="text" />
    </div>
    <div>
        <label asp-for="LastName"></label>
        <input asp-for="LastName" type="text" />
    </div>
    <div><button>Submit</button></div>
</form>

ADNUG.Lightning.Web/Views/Person/Index.cshtml
@using ADNUG.Lightning.Web.Models
@model ADNUG.Lightning.Web.Models.PersonEditModel

@{
    ViewBag.Title = "ModelExpression Example";
    Layout = "_Layout";
}

<h2>ModelExpression Example</h2>

<form asp-controller="Person" asp-action="Index" method="post">
    
    <form-text-input ad-for="FirstName"></form-text-input>
    <form-text-input ad-for="LastName"></form-text-input>
    <form-text-input ad-for="Age"></form-text-input>
    <br />  
    <formbutton type="submit" bg-color="primary"></formbutton>

</form>

ADNUG.Lightning.Web/Views/Shared/Components/DirectoryGrid/Default.cshtml
@using ADNUG.Lightning.Web.Models.DataTransferObjects
@model  ADNUG.Lightning.Web.Models.DataTransferObjects.DriveInfoDto

<hr /> 

@if (Model.FolderGrid.Any())
{
    <div id="crumbs" class="col-xs-12">@Model.BreadCrumbTrail</div>

    <bootstrap-table>
        <tbody>
            @foreach (var row in Model.FolderGrid)
            {
                <tr>

                    @foreach (var cell in row)
                    {
                        <td>
                            @if (@cell.Empty)
                            {
                                <span class="folder-under-text">@cell.Name</span>
                            }
                            else
                            {
                                <a class="lnk" href="@("/api/HardDrive/GetContents")" data-fullpath="@cell.FullPath" data-type="@(cell.Icon == "fa-folder" ? "folder" : "file")">
                                    <span class="fa @(cell.Icon) @(cell.Icon == "fa-folder" ? "folder" : "file")"></span>
                                    <br />
                                    <span class="folder-under-text">@cell.Name</span>
                                </a>
                            }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </bootstrap-table>

}
else
{
    <div style="margin-top: 20px">The was an access violation for one of the directories.</div>
}

ADNUG.Lightning.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ADNUG.Lightning.AspCore</title>

    <environment names="Development">
        <link rel="stylesheet" type="text/css" href="~/css/sweetalert.css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ADNUG.Lightning.AspCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Person" asp-action="BuiltInTagHelpers">Built In Tag Helpers Example</a></li>
                    <li><a asp-area="" asp-controller="Person" asp-action="Index">Model Expression Example</a></li>
                    <li><a asp-area="" asp-controller="FolderBrowser" asp-action="Index">Folder Browser</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Lawyers are boring people.</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/classList.min.js" asp-append-version="true"></script>
        <script src="~/js/sweetalert.min.js" asp-append-version="true"></script>
        <script src="~/js/vanillajs.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>